enum characterSheetFields {
  Name = "Name= ",
  Level = "Level= ",
  Age = "Age= ",
  Speed = "Speed= ",
  Strength = "Strength= ",
  Dexterity = "Dextery= ",
  Constituion = "Constitution= ",
  Intelligence = "Intelligence= ",
  Wisdom = "Wisdom= ",
  Charisma = "Charisma= ",
  ArmorClass = "Armorclass= ",
  Hp = "HP= ",
  ClassDC = "Class DC= ",
  Perception = "Perception= ",
  Arcana = "Arcana= ",
  Athletics = "Athletics= ",
  Crafting = "Crafting= ",
  Deception = "Deception= ",
  Diplomacy = "Diplomacy= ",
  Intimidation = "Intimidation= ",
  Lore = "Lore= ",
  Medicine = "Medicine= ",
  Natrure = "Nature= ",
  Occultism = "Occultism= ",
  Performance = "Performance= ",
  Religion = "Religion= ",
  Society = "Society= ",
  Stealth = "Stealth= ",
  Survival = "Survival= ",
  Thievery = "Thievery= ",
}

export { characterSheetFields };
